### ISSUE TITLE
Ram patch upload 

### ISSUE THREAD

**Issue by yjhonga** [sparkfunX/Qwiic_Time-of-Flight-TMF8801#2]
follow the step as below until step 6 
The Bootloader application allows to download an encrypted image and start the downloaded image.
To download an encrypted image you need to perform the following steps:
1. Sent the DOWNLOAD_INIT command: S 41 W 08 14 01 29 C1 P
2. Set up the RAM address pointer with command ADDR_RAM.
3. Send consecutive data with the command W_RAM.
4. If you need to move the address pointer use command ADDR_RAM
5. Send consecutive data with the command W_RAM.
6. Send the command RAMREMAP_RESET to start the downloaded application

**Send the command RAMREMAP_RESET to start the downloaded application
1.	CMD_STATUS register  0x08 input{0x11,0x00,0xEE} feedback read 0x08 {0x41,0x10,0xBE}
I just know 0x41 mean busy ,but I couldn’t understand what wrong is it? Is it mean the Patch is wrong? And how to do**

**Comment by PPVJM** [comment]
I am still trying to solve this issue. I have contacted the sensor manufacturer and I am working on it. Thank you for your understanding and patience.

**Comment by yjhonga** [comment]
Thanks a lot ~
I could provide RAM firmware raw data on excel
maybe it could help you to finish the coding
[TMF8801 RAM PATCH RAW DATA.xlsx](https://github.com/sparkfunX/Qwiic_Time-of-Flight-TMF8801/files/7018497/TMF8801.RAM.PATCH.RAW.DATA.xlsx)
[Ram patch.txt](https://github.com/sparkfunX/Qwiic_Time-of-Flight-TMF8801/files/7037588/Ram.patch.txt)

**Comment by yjhonga** [comment]
I finish the coding but I only have the Arduino UNO (Not enough memory)
If you need I could send the file for you
